image: mardy/qt:xenial-qt512

cache:
  key: apt-cache
  paths:
  - apt-cache/

stages:
  - build
  - test

before_script:
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - >-
      apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y
      xvfb lcov gcovr
      libglu1-mesa-dev libxrender1

build_5.12:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake CONFIG+=debug CONFIG+=coverage ..
    - make -j 4
  artifacts:
    paths:
      - build/

test_5.12:
  stage: test
  script:
    - find build | xargs touch # Avoid rebuilding
    - export TMPDIR=$(pwd)/tmpdir
    - mkdir $TMPDIR
    - cd build
    - make install
    - make coverage-html
  dependencies:
    - build_5.12
  artifacts:
    when: always
    paths:
      - build/coverage-html/
      - tmpdir
