image: ubuntu:bionic

cache:
  key: apt-cache
  paths:
  - apt-cache/

before_script:
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - apt-get update -yq
  - >-
      apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y
      qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-window2
      qt5-qmake qtbase5-dev qtchooser
      qtdeclarative5-dev qtquickcontrols2-5-dev qttools5-dev
      lcov gcovr pkg-config xvfb

build_desktop:
  stage: build
  script:
    - export QT_SELECT=qt5
    - mkdir build
    - cd build
    - qmake CONFIG+=debug CONFIG+=coverage ..
    - make -j 4
  artifacts:
    paths:
      - build/

test_desktop:
  stage: test
  script:
    - find build | xargs touch # Avoid rebuilding
    - cd build
    - make install
    - make coverage-html
  dependencies:
    - build_desktop
  artifacts:
    paths:
      - build/coverage-html/
